version: '3'

services:
  app:
    build: ./app
    ports: 
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      - app-network


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge